# These are supported funding model platforms

github: # madilraza  #ShahzaibNahar
patreon:  madilraza ShahzaibNahar
open_collective: Muhammad Adil Raza, Shahzaib Nahar
ko_fi: madilraza, shahzaibnahar
tidelift:  npm/babel
community_bridge: cloud-foundry
liberapay:  madilraza
issuehunt:  madilraza
otechie: madilraza
custom:   ['https://github.com/users/madilraza/projects/3', 'https://github.com/users/madilraza/projects/2']
